routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('products','ProductController');
});

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use Spatie\Permission\Models\Role;

class SettingController extends Controller
{
    public function contactDetail()
    {

    }

    public function passwordEpp()
    {

    }

    public function users(Request $request,$id=null)
    {
        if($id==null){
            $data = User::orderBy('id','DESC')->paginate(5);
            return view('settings.users',compact('data'))
                ->with('i', ($request->input('page', 1) - 1) * 5);
        }else{
            $user = User::find($id);
            $roles = Role::pluck('name','name')->all();
            $userRole = $user->roles->pluck('name','name')->all();

            return view('settings.usersEdit',compact('user','roles','userRole'));
        }
    }
}

resources/views/settings/contactDetail.blade.php
@extends('layouts.joli.main')

@section('title',' Contact Detail')

@section('content')
<div class="row">
    <div class="col-lg-12 col-md-12">
        
        <div class="panel panel-default">
            <div class="panel-body">
               
               <div class="panel panel-success">
                     <div class="panel-heading">
                           <h3 class="panel-title">General Information</h3>
                     </div>
                     <div class="panel-body">
                           <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>Contact Name/Role</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Organozation</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>Trading Name</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Website</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                           </div>
                     </div>
               </div>
               
               <br>
               
               <div class="panel panel-success">
                     <div class="panel-heading">
                           <h3 class="panel-title">Address & Telephone</h3>
                     </div>
                     <div class="panel-body">
                           <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Telephone</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Fax</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>City</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>State Province</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Postcode</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Country</label>
                                        
                                        <select name="" id="input" class="form-control" required="required">
                                            <option value=""></option>
                                        </select>
                                        
                                    </div>    
                                </div>
                           </div>
                     </div>
               </div>
               
               <br>
               
               <div class="panel panel-success">
                     <div class="panel-heading">
                           <h3 class="panel-title">Notification Email Address</h3>
                     </div>
                     <div class="panel-body">
                           <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>Email Primer</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    &nbsp;
                                </div>
                                <div class="col-lg-12 col-md-12" style="padding:10px 0;">
                                    &nbsp;
                                    <hr>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>Billing Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Transfer Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Security Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>Launch Notification Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Legar Contract Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                           </div>
                     </div>
               </div>
               
               <br>

               <div class="panel panel-success">
                     <div class="panel-heading">
                           <h3 class="panel-title">Optional Notification Email Address</h3>
                     </div>
                     <div class="panel-body">
                           <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>MArketing Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Oprational Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>Credit Limit Warning Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Deletion Email Address</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                           </div>
                     </div>
               </div>
            </div>
        </div>
        
    </div>
</div>
@endsection

@section('js_plugin')
<script type='text/javascript' src="{{ asset('joli/js/plugins/icheck/icheck.min.js') }}"></script>        
<script type="text/javascript" src="{{ asset('joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>
{{-- <script type="text/javascript" src="{{ asset('joli/js/plugins/scrolltotop/scrolltopcontrol.js') }}"></script> --}}

@endsection

resources/views/settings/editProfile.blade.php
@extends('layouts.joli.main')

@section('title',' Current User : user')

@section('content')
<div class="row">
    <div class="col-lg-12 col-md-12">
        
        <div class="panel panel-default">
            <div class="panel-body">
               
               <div class="panel panel-success">
                     <div class="panel-heading">
                           <h3 class="panel-title">Password</h3>
                     </div>
                     <div class="panel-body">
                           <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    
                                    User Information
                                    <hr>
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Full Name</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    Change Password
                                    <hr>
                                    <div class="form-group">
                                        <label>Current Password</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>New Password</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                    <div class="form-group">
                                        <label>Confirm New Password</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                
                                </div>
                           </div>
                     </div>
               </div>
               
               <br>
            </div>
        </div>
        
    </div>
</div>
@endsection

@section('js_plugin')
<script type='text/javascript' src="{{ asset('joli/js/plugins/icheck/icheck.min.js') }}"></script>        
<script type="text/javascript" src="{{ asset('joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>
{{-- <script type="text/javascript" src="{{ asset('joli/js/plugins/scrolltotop/scrolltopcontrol.js') }}"></script> --}}

@endsection

resources/views/settings/passwordEpp.blade.php
@extends('layouts.joli.main')

@section('title',' Password')

@section('content')
<div class="row">
    <div class="col-lg-12 col-md-12">
        
        <div class="panel panel-default">
            <div class="panel-body">
               
               <div class="panel panel-success">
                     <div class="panel-heading">
                           <h3 class="panel-title">Password</h3>
                     </div>
                     <div class="panel-body">
                           <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                        <label>EPP Password</label>
                                        <input type="email" class="form-control">
                                    </div>    
                                </div>
                                <div class="col-lg-6 col-md-6">
                                
                                </div>
                           </div>
                     </div>
               </div>
               
               <br>
            </div>
        </div>
        
    </div>
</div>
@endsection

@section('js_plugin')
<script type='text/javascript' src="{{ asset('joli/js/plugins/icheck/icheck.min.js') }}"></script>        
<script type="text/javascript" src="{{ asset('joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>
{{-- <script type="text/javascript" src="{{ asset('joli/js/plugins/scrolltotop/scrolltopcontrol.js') }}"></script> --}}

@endsection

resources/views/settings/users.blade.php
@extends('layouts.joli.main')

@section('title',' List Users')
@section('content')
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                    <input type="text" name="" id=""> <input type="button" value="Search">
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="pull-right">
                            <a class="btn btn-success" href="{{ route('users.create') }}"> Create New User</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-actions">
                        <tr>
                            <!-- <th>No</th> -->
                            <th>Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Roles</th>
                            <th>Status</th>
                            <th>Created Date</th>
                            <th width="280px">Action</th>
                        </tr>
                        @foreach ($data as $key => $user)
                        <tr>
                            <!-- <td>{{ ++$i }}</td> -->
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->username }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                @if(!empty($user->getRoleNames()))
                                @foreach($user->getRoleNames() as $v)
                                <label class="badge badge-success">{{ $v }}</label>
                                @endforeach
                                @endif
                            </td>
                            <td>{{ $user->status }}</td>
                            <td>{{ $user->created_at }}</td>
                            <td>
                                <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">Show</a>
                                <a class="btn btn-primary" href="{{ route('setting.user.edit',$user->id) }}">Edit</a>
                                {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
                {!! $data->render() !!}
            </div>
        </div>
    
    </div>
</div>


@endsection

@section('js_plugin')
<script type='text/javascript' src="{{ asset('joli/js/plugins/icheck/icheck.min.js') }}"></script>        
<script type="text/javascript" src="{{ asset('joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>
{{-- <script type="text/javascript" src="{{ asset('joli/js/plugins/scrolltotop/scrolltopcontrol.js') }}"></script> --}}

<script type="text/javascript" src="{{ asset('joli/js/plugins/morris/raphael-min.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/morris/morris.min.js') }}"></script>       
<script type="text/javascript" src="{{ asset('joli/js/plugins/rickshaw/d3.v3.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/rickshaw/rickshaw.min.js') }}"></script>
<script type='text/javascript' src="{{ asset('joli/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script type='text/javascript' src="{{ asset('joli/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>                
<script type='text/javascript' src="{{ asset('joli/js/plugins/bootstrap/bootstrap-datepicker.js') }}"></script>                
<script type="text/javascript" src="{{ asset('joli/js/plugins/owl/owl.carousel.min.js') }}"></script>                 

<script type="text/javascript" src="{{ asset('joli/js/plugins/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/daterangepicker/daterangepicker.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
@endsection

resources/views/settings/usersEdit.blade.php
@extends('layouts.joli.main')

@section('title',' List Users')
@section('content')
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                    <input type="text" name="" id=""> <input type="button" value="Search">
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="pull-right">
                            <a class="btn btn-success" href="{{ route('users.create') }}"> Create New User</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id]]) !!}
                <div class="row">
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <strong>Username:</strong>
                            {!! Form::text('username', null, array('placeholder' => 'Username','class' => 'form-control','disabled')) !!}
                        </div>
                        <div class="form-group">
                            <strong>Email:</strong>
                            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <strong>Name:</strong>
                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                        </div>
                        <div class="form-group">
                            <strong>Role:</strong>
                            {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    
    </div>
</div>


@endsection

@section('js_plugin')
<script type='text/javascript' src="{{ asset('joli/js/plugins/icheck/icheck.min.js') }}"></script>        
<script type="text/javascript" src="{{ asset('joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>
{{-- <script type="text/javascript" src="{{ asset('joli/js/plugins/scrolltotop/scrolltopcontrol.js') }}"></script> --}}

<script type="text/javascript" src="{{ asset('joli/js/plugins/morris/raphael-min.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/morris/morris.min.js') }}"></script>       
<script type="text/javascript" src="{{ asset('joli/js/plugins/rickshaw/d3.v3.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/rickshaw/rickshaw.min.js') }}"></script>
<script type='text/javascript' src="{{ asset('joli/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script type='text/javascript' src="{{ asset('joli/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>                
<script type='text/javascript' src="{{ asset('joli/js/plugins/bootstrap/bootstrap-datepicker.js') }}"></script>                
<script type="text/javascript" src="{{ asset('joli/js/plugins/owl/owl.carousel.min.js') }}"></script>                 

<script type="text/javascript" src="{{ asset('joli/js/plugins/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/daterangepicker/daterangepicker.js') }}"></script>
<script type="text/javascript" src="{{ asset('joli/js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
@endsection